# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Final Group Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Final Group Project
    pod 'Cosmos', '~> 18.0'
    pod 'Alamofire', '~> 4.5'

end
